gnu: patman: Fix execution.
Before this change, patman would fail at run time with "AttributeError: module
'patman.__main__' has no attribute 'run_patman'" since the last U-Boot update.

* gnu/packages/bootloaders.scm (patman) [arguments]
<phases>: New patch-pyproject.toml phase.