gnu: ipxe: Update to 1.21.1-2.de8a082.
This fixes

    error: in phase 'build': uncaught exception:

while building ipxe-qemu.

* gnu/packages/bootloaders.scm (ipxe): Update commit to
de8a0821c7bc737e724fa3dfb6d89dc36f591d7a.  Bump revision and timestamp.

Change-Id: I352a8451ba9da912f023802f1f31e5e311705ba2